config/routes.rb
Rails.application.routes.draw do

  resources :personas
  resources :administrar_usuarios
  resources :roles
  resources :curriculums
  resources :profesiones
  resources :experiencias_laborales
  resources :informaciones_academicas
  resources :informacion_academicas
  resources :informacion_academica
  resources :experiencia_laboral
  resources :estudios_complementarios
  resources :referencias_personales
  resources :informacion_academica
  devise_for :users
  root to: "profesiones#index"

  resources :airports , :path => "aeropuertos"
  resources :cities , :path => "ciudades"
  resources :arles
  resources :epses
  resources :users, :path => "usuarios"
  resources :roles, :path => "roles"
  resources :departments, :path => "departamentos"
  resources :countries, :path => "paises"
  resources :arles, :path => "arls"
  resources :epses, :path => "eps"
  

  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'
  
  resources :products
  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  resources :patients, :path => "pascientes", only: [:new, :create, :index, :destroy, :show, :edit, :update]  do
    resources :clinic_histories, :path => "historias_clinicas", only: [:new, :create, :index, :destroy, :show, :edit, :update] do
      resources :steps, only: [:show, :update, :edit], controller: 'clinic_history/steps'
      resources :progress_notes, :path => "nota_de_evolucion"
    end
  end

end

app/models/progress_note.rb
# == Schema Information
#
# Table name: progress_notes
#
#  id                :integer          not null, primary key
#  patient_name      :string
#  patient_document  :string
#  type_document     :string
#  age               :integer
#  medical_record    :string
#  description       :text
#  clinic_history_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class ProgressNote < ActiveRecord::Base
  belongs_to :clinic_history

  def self.search(search)
    where("patient_name like '%#{search}%'  or patient_document like '%#{search}%'")
  end



end

app/controllers/progress_notes_controller.rb
class ProgressNotesController < ApplicationController
  # before_action :set_progress_note, only: [:show, :edit, :update, :destroy]
  before_filter :set_progress_note

  # GET /progress_notes
  # GET /progress_notes.json
  def index
    @progress_notes =  ProgressNote.search(params[:search]).page(params[:page]).per_page(2)
  end

  # GET /progress_notes/1
  # GET /progress_notes/1.json
  def show
  end

  # GET /progress_notes/new
  def new
    @progress_note = ProgressNote.new
  end

  # GET /progress_notes/1/edit
  def edit
  end

  # POST /progress_notes
  # POST /progress_notes.json
  def create
    @progress_note = ProgressNote.new(progress_note_params)
   
    @progress_note.clinic_history_id = @clinic_history.id

    respond_to do |format|
      if @progress_note.save
        format.html { redirect_to patient_clinic_history_progress_note_path(@patient, @clinic_history, @progress_note), notice: 'Historia Clinica was successfully created.' }

        format.json { render :show, status: :created, location: @progress_note }
      else
        format.html { render :new }
        format.json { render json: @progress_note.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /progress_notes/1
  # PATCH/PUT /progress_notes/1.json
  def update
    respond_to do |format|
      if @progress_note.update(progress_note_params)
        format.html { redirect_to @progress_note, notice: 'Progress note was successfully updated.' }
        format.json { render :show, status: :ok, location: @progress_note }
      else
        format.html { render :edit }
        format.json { render json: @progress_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progress_notes/1
  # DELETE /progress_notes/1.json
  def destroy
    @progress_note.destroy
    respond_to do |format|
      format.html { redirect_to progress_notes_url, notice: 'Progress note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress_note
      @clinic_history = ClinicHistory.find(params[:clinic_history_id])
      @patient = Patient.find(params[:patient_id])
      @progress_note = ProgressNote.find(params[:id]) if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_note_params
      params.require(:progress_note).permit(:patient_name, :patient_document, :type_document, :age, :medical_record, :description, :clinic_history_id)
    end
end

app/helpers/progress_notes_helper.rb
module ProgressNotesHelper
end

app/views/progress_notes/edit.html.erb
<h1>Editing Progress Note</h1>

<%= render 'form' %>

<%= link_to 'Show', patient_clinic_history_progress_notes_path(@patient,@clinic_history,@progress_note) %> |
<%= link_to 'Back', patient_clinic_history_progress_notes_path(@patient,@clinic_history,@progress_note) %>

app/views/progress_notes/index.html.erb
<br/>
<div align="center">
 
<%= link_to image_tag('Crud/return.png', :title => "Listado historias clinicas"),  patient_clinic_histories_path(@patient,@clinic_history), :class => 'btn btn-link'%>

  <h1>Listado de  <span>Notas de Evolución de </span><%= @patient.first_name %></h1>
</div>

  <%= form_tag request.path, :method => 'get', :class => '' do %>

<div id="page" class="middle">
  
  <div class="wrapper">
    <div class="table">
      
      <div class="table-cell-flex">
          <%= text_field_tag :search, params[:search], :placeholder => "Ingresa Nombre o Cedula", :class => 'form-control' %>
      </div>
      
      <!-- random google image -->
      <div class="table-cell-fixed"> 
      <%= button_tag(type: "submit", class: "btn btn-link") do %>
        <i class="glyphicon glyphicon-search blanco"  style="font-size: 20px;"></i>
      <% end %>
      </div>
      
    </div>
  </div>
  
</div>
<% end %>


<style type="text/css">

#page {
  position: relative;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  text-align: center;
}
#page .wrapper {
  width: 60%;
}
#page .wrapper .table {
  display: table;
  width: 100%;
  margin: auto;
  background: linear-gradient(to bottom, #167f92 0%, #167f92 100%);
  border-radius: 6px;
  padding: 5px;
  box-shadow: 1px 1px 2px #167f92;
}
#page .wrapper .table > * {
  vertical-align: middle;
}
#page .wrapper .table .table-cell-flex {
  display: table-cell;
  width: 100%;
}
#page .wrapper .table .table-cell-flex input {
  color: #167f92;
  padding: 10px;
  width: 100%;
  box-sizing: border-box;
  border: 1px solid #167f92;
  box-shadow: inset 1px 1px 5px #167f92;
}
#page .wrapper .table .table-cell-fixed {
  display: table-cell;
  white-space: nowrap;
}
#page .wrapper .table .table-cell-fixed a {
  margin-left: 5px;
  display: inline-block;
  width: 32px;
  height: 32px;
  text-align: middle;
  transition: all 0.2s linear;
}
#page .wrapper .table .table-cell-fixed a:hover {
  background: #167f92;
}
#page .wrapper .table .table-cell-fixed a:active {
  box-shadow: inset 0px 0px 5px #167f92;
}
.middle:before {
  content: '';
  display: inline-block;
  vertical-align: middle;
  height: 100%;
}
.middle > * {
  display: inline-block;
  vertical-align: middle;
}

</style>


<br/>






<table class="responstable">
  
  <tr>
    <th>Nombre Paciente</th>
    <th>Documento Paciente</th>
    <th>Edad</th>
    <th>Registro Medico</th>
    <th>Descripcion</th>
    <th>Opciones</th>
  </tr>
  
<% @progress_notes.each do |progress_note| %>

  <tr>
    <td><%= progress_note.patient_name %></td>
    <td><%= progress_note.patient_document %></td>
    <td><%= progress_note.age %></td>
    <td><%= progress_note.medical_record %></td>
    <td><%= progress_note.description %></td>

    <td><%= link_to  image_tag('Crud/show.png', :title => "ver nota de evolución"), patient_clinic_history_progress_note_path(@patient,@clinic_history,progress_note), :class => 'btn btn-link' %>
    <%= link_to image_tag('Crud/edit.png', :title => "editar nota de evolución"), edit_patient_clinic_history_progress_note_path(@patient,@clinic_history,progress_note),  :class => 'btn btn-link'%></td>

  </tr>
  
<% end %>

</table>

<%= link_to image_tag('Crud/new.png', :title => "nueva nota de evolución"),  new_patient_clinic_history_progress_note_path(@patient,@clinic_history,@progress_note), :class => 'btn btn-link'%></td>

<div align="center">
  <%= will_paginate @progress_notes, renderer: BootstrapPagination::Rails %>
</div>



<style type="text/css">
  /*

RESPONSTABLE 2.0 by jordyvanraaij
  Designed mobile first!

If you like this solution, you might also want to check out the 1.0 version:
  https://gist.github.com/jordyvanraaij/9069194

*/
.responstable {
  margin: 1em 0;
  width: 100%;
  overflow: hidden;
  background: #FFF;
  color: #024457;
  border-radius: 10px;
  border: 1px solid #167F92;
}
.responstable tr {
  border: 1px solid #D9E4E6;
}
.responstable tr:nth-child(odd) {
  background-color: #EAF3F3;
}
.responstable th {
  display: none;
  border: 1px solid #FFF;
  background-color: #167F92;
  color: #FFF;
  padding: 1em;
}
.responstable th:first-child {
  display: table-cell;
  text-align: center;
}
.responstable th:nth-child(2) {
  display: table-cell;
}
.responstable th:nth-child(2) span {
  display: none;
}
.responstable th:nth-child(2):after {
  content: attr(data-th);
}
@media (min-width: 480px) {
  .responstable th:nth-child(2) span {
    display: block;
  }
  .responstable th:nth-child(2):after {
    display: none;
  }
}
.responstable td {
  display: block;
  word-wrap: break-word;
  max-width: 7em;
}
.responstable td:first-child {
  display: table-cell;
  text-align: center;
  border-right: 1px solid #D9E4E6;
}
@media (min-width: 480px) {
  .responstable td {
    border: 1px solid #D9E4E6;
  }
}
.responstable th, .responstable td {
  text-align: left;
  margin: .5em 1em;
}
@media (min-width: 480px) {
  .responstable th, .responstable td {
    display: table-cell;
    padding: 1em;
  }
}

body {
  padding: 0 2em;
  font-family: 'Lato', Arial, sans-serif;
  color: #024457;
  background: #f2f2f2;
}

h1 {
  font-family: Verdana;
  font-weight: normal;
  color: #024457;
}
h1 span {
  color: #167F92;
}

</style>

app/views/progress_notes/new.html.erb
<h1>New Progress Note</h1>

<%= render 'form' %>

app/views/progress_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre del Paciente:</strong>
  <%= @progress_note.patient_name %>
</p>

<p>
  <strong>Documento del Paciente:</strong>
  <%= @progress_note.patient_document %>
</p>

<p>
  <strong>Type document:</strong>
  <%= @progress_note.type_document %>
</p>

<p>
  <strong>Edad:</strong>

  <% edad =  ((Time.now - @patient.birthdate.to_time)/60/60/24).to_i  %>
      <% edad2 =  ((Time.now - @patient.birthdate.to_time)/60/60/24/31).to_i  %>
      <% edad3 =  ((Time.now - @patient.birthdate.to_time)/60/60/24/365).to_i  %>
      
      <% if  edad < 31 %>
          Tiene <%= edad %> dias de vida
      <% elsif edad >= 31 && edad < 365 %>
          Tiene <%= edad2 %> meses de vida
      <% elsif edad >= 365 %>
          Tiene <%= edad3 %> años de vida
      <% end %>
</p>

<p>
  <strong>Registro Medico:</strong>
  <%= @progress_note.medical_record %>
</p>

<p>
  <strong>Description:</strong>
  <%= @progress_note.description %>
</p>

<p>
  <strong>Historia Clinica:</strong>
  <%= @progress_note.clinic_history.id %>
</p>

<%= link_to 'Edit', edit_patient_clinic_history_progress_note_path(@patient,@clinic_history,@progress_note) %> |
<%= link_to 'Back', patient_clinic_history_progress_notes_path(@patient,@clinic_history,@progress_note) %>