config/routes.rb
Rails.application.routes.draw do

  resources :personas
  resources :administrar_usuarios
  resources :roles
  resources :curriculums
  resources :profesiones
  resources :experiencias_laborales
  resources :informaciones_academicas
  resources :informacion_academicas
  resources :informacion_academica
  resources :experiencia_laboral
  resources :estudios_complementarios
  resources :referencias_personales
  resources :informacion_academica
  devise_for :users
  root to: "profesiones#index"

  resources :airports , :path => "aeropuertos"
  resources :cities , :path => "ciudades"
  resources :arles
  resources :epses
  resources :users, :path => "usuarios"
  resources :roles, :path => "roles"
  resources :departments, :path => "departamentos"
  resources :countries, :path => "paises"
  resources :arles, :path => "arls"
  resources :epses, :path => "eps"
  

  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'
  
  resources :products
  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  resources :patients, :path => "pascientes", only: [:new, :create, :index, :destroy, :show, :edit, :update]  do
    resources :clinic_histories, :path => "historias_clinicas", only: [:new, :create, :index, :destroy, :show, :edit, :update] do
      resources :steps, only: [:show, :update, :edit], controller: 'clinic_history/steps'
      resources :progress_notes, :path => "nota_de_evolucion"
    end
  end

end

app/models/airport.rb
# == Schema Information
#
# Table name: airports
#
#  id         :integer          not null, primary key
#  name       :string
#  city_id    :integer
#  department :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Airport < ActiveRecord::Base
  belongs_to :city
  has_many :clinic_histories




   def self.search(search)
    where("name like '%#{search}%'  or department like '%#{search}%'")
  end

end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: [:show, :edit, :update, :destroy]
  before_action :get_all, only: [:index, :create, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
     @airports = Airport.search(params[:search]).page(params[:page]).per_page(10)
    respond_to do |format|
      format.html
      format.json
    end
  end
  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @airport = Airport.find_by(id: params[:id])
  end

  # GET /epss/new
  def new
    @airport = Airport.new
  end

  # GET /epss/1/edit
  def edit
    @airport = Airport.find_by(id: params[:id])
  end

  # POST /epss
  # POST /epss.json
  def create
    @airport = Airport.create(airport_params)

  end

  # PATCH/PUT /epss/
  # PATCH/PUT /epss/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: 'eps was successfully updated.' }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /epss/1
  # DELETE /epss/1.json
  def destroy
    @airport = Airport.find_by(id: params[:id])
    if @airport.destroy
      redirect_to airports_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    def get_all
      @airports = Airport.search(params[:search]).page(params[:page]).per_page(10)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airport_params
      params.require(:airport).permit(:name, :city_id, :department)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_comment.html.erb
<p>
  <strong>First name:</strong>
  <%= best_in_place  @arl, :name %>
</p>

app/views/airports/_display.html.erb
<div>

<div>
    <div>
    <table class="table table-bordered">
    <thead>




<table class="table table-bordered" style="margin-top:-30px;">
  

<tr>
      <th  colspan="6">
        
              <%= form_tag request.path, :method => 'get' do %>
  
<div>
  <div class="row">

    <div class="col-lg-5 ">

            <div class="input-group custom-search-form">
              <%= text_field_tag :search, params[:search], :placeholder => "Busca por el Nombre", :class => 'form-control' %>
              <span class="input-group-btn">


<%= button_tag(type: "submit", class: "btn principal nn") do %>
              <span class="glyphicon glyphicon-search"></span>
                          <% end %>

             </span>
             </div><!-- /input-group -->
        </div>
  </div>
</div>
                    <% end %>



      </th>

</tr>


  <tr class="header">
    <th>Airport #</th>
    <th>Nombre</th>
    <th>Ciudad</th>
    <th>Departamento</th>
    <th>Fecha</th>
    <th>Opciones</th>
  </tr>
  
  
<% @airports.each do |airport| %>

  <tr>

    <td><%= airport.id %></td>
    <td><%= best_in_place airport, :name, :ok_button => "Guardar", :ok_button_class => "btn btn-success", :cancel_button => 'Cerrar', :cancel_button_class => "btn btn-primary"  %></td>
    <td><%= airport.city.name %></td>
    <td><%= airport.department %></td>
    <td><%= airport.created_at.strftime('%b %d. %Y') %></td>

<td>

    <%= link_to 'Editar', edit_airport_path(airport),  :rel => "tooltip", :title => "Editar", :class => 'btn btn-primary btn-xs color_blanco principal' %>
    <%= link_to 'Eliminar', airport, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs color_blanco ' %>







</td>

  </tr>
  
<% end %>

</table>


<style type="text/css">

.eliminar {
    color: red;
}

</style>





<style type="text/css">


.pagination>.active>a, .pagination>.active>span, .pagination>.active>a:hover, .pagination>.active>span:hover, .pagination>.active>a:focus, .pagination>.active>span:focus{
      z-index: 2;
    color: #fff;
    cursor: default;
    background-color: #20B4BF !important;
    border-color: #20B4BF !important;
}

.principal{
  background-color: #20B4BF !important;
  color: #ffffff !important;
  border-color: #22BDC8;
}


.header{
  background-color: #F2F2F2;
  border-color: #22BDC8;
}

body {
  padding: 0 2em;
  font-family: 'Lato', Arial, sans-serif;
  background: #ffffff !important;
}

h1 {
  font-family: Verdana;
  font-weight: normal;
  color: #024457;
}
h1 span {
  color: #167F92;
}

</style>



</div>
<style type="text/css">
    @import url(http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css);
body{margin-top:20px;}
.fa-fw {width: 2em;}
</style>

app/views/airports/_form.html.erb
<div class="container-fluid">
    
      <div class="col-md-12 col-md-offset" style = "margin-bottom:10px;">
      
          <div class="panel-body navbar navbar-default">

            <%= simple_form_for(@airport,html: { class: "form-inline pull-right"} ,:remote => true) do |f| %>
                   <div class="form-group">
                  <label class='control-label new_blog'>Nombre:</label>                
                  <%= f.input :name,  placeholder: 'Campo Obligatorio', input_html: {class: "form-control new_blog"}, label: false,  :required => true %>

                    </div>
  

                  <div class="form-group">
                      <label class='control-label new_blog'>Departamento:</label>                
                          <%= f.input :department,
                              prompt:       'Campo Obligatorio',
                              collection: @airport.select_department.sort,
                              error: false, label: false, 
                              input_html:   {class: 'form-control'} %>  
                            

                  </div>

                 
                <div class="form-group">
                 
                  <label class='control-label new_blog'>Ciudad:</label>      
                  <div class="input">        
                        <%= f.collection_select :city_id, City.all, :id, :name, {prompt: "Campo Obligatorio"}, {class: "form-control"} %>
 </div>
                 </div>

                <div class="form-group">
                  <label class='control-label new_blog'></label>      
                  <div class="input">        
                        <%= f.submit "Guardar", :class => 'btn btn-primary' %>
                  </div>
                 </div>

              <% end %>
          </div>
      </div>
    </div>
 

app/views/airports/create.js.erb
$(".new_blog").slideUp(350);
$('#tasks').html("<%= j render partial: 'display'%>");

app/views/airports/edit.html.erb
<h1>Actualizar Aeropuerto</h1>

<%= render 'form' %>

<%= link_to 'Regresar', airports_path, :class => "btn btn-success color_blanco" %>

app/views/airports/get.js.erb
alert("hola");

app/views/airports/index.html.erb
<br/><br/><br/><br/>

<div class="row">
<div class="full col-sm-9 full2">





    <span  class="btn btn-link btn-xs  pull-left pagination pagination"><h1 class="title">Aeropuertos</h1></span>


    <span class="btn btn-link btn-xs pull-right ">  <%= will_paginate @airports, renderer: BootstrapPagination::Rails %>
</span>

    <span  class="btn btn-link btn-xs  pagination pagination pull-right"><%= link_to 'Nuevo Aeropuerto', new_airport_path, remote: true, :class => "btn  principal" %></span>



<div class="row new_blog">
<div class="col-md-6" id="task-form" style="display:none;"></div>
</div>







<div class="row">
  <div class="col-md-12 " id="tasks">
    <%= render partial: "display" %>
  </div>
</div>
</div>





                                    
             

app/views/airports/new.html.erb
<%- model_class = Airport -%>
<div class="page-header">
</div>
<%= render :partial => 'form' %>

app/views/airports/new.js.erb
$('.new_blog').html("<%= j (render 'form') %>");
$('.new_blog').slideDown(350);

app/views/airports/show.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<div class="wrapper">
  <div class="info-panel">
    <div class="logo"></div>
    <div class="info-panel__main">
      <h1>Aeropuerto Ingresado Satisfactoriamente</h1>
      <br/>
      <h2>Gracias por Ingresar la información</h2>
            <div   align="center">

                <h3 class="panel-title-fd">Datos del aeropuerto # <%= @airport.id %></h3>






                <div class="media">
                  
                  <%= image_tag "Models/airplane.png", :class => 'imagelink' %>

                  <style type="text/css">
                    .imagelink{
                      width: 104px; height: 104px;
                    }
                  </style>



                  <div class="media-body">
                    <h4 class="media-heading color_blanco"><b>Nombre:</b> <%= @airport.name %></h4>
                    <h4 class="media-heading color_blanco"><b>Departamento:</b> <%= @airport.label_department %></h4>
                    <h4 class="media-heading color_blanco"><b>Ciudad:</b> <%= @airport.city.name %></h4>

                  </div>


              </div>

<br/>
<div align="center">
  
              <div class="ui-group-buttons">

                <%= link_to "Editar Aeropuerto", edit_airport_path(@airport), :class => 'button btn btn-success blanco'%>

                <div class="or"></div>

                <%= link_to  "Regresar al listado", airports_path,   :class => 'button btn btn-primary blanco' %>
</div>
        </div>
    </div>
  </div>
<br/><br/>

    







      </div>
        </div>




</div>






<style type="text/css">
  @import url(http://fonts.googleapis.com/css?family=Open+Sans:700);
.panel-heading-fd{
    font-family: 'Open Sans', Helvetica, sans-serif;
    background: #39b1cc;
    background: -moz-linear-gradient(top, #51bbd2 0%, #2d97af 100%);
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #51bbd2), color-stop(100%, #2d97af));
    background: -webkit-linear-gradient(top, #51bbd2 0%, #2d97af 100%);
    background: -o-linear-gradient(top, #51bbd2 0%, #2d97af 100%);
    background: -ms-linear-gradient(top, #51bbd2 0%, #2d97af 100%);
    background: linear-gradient(to bottom, #51bbd2 0%, #2d97af 100%);
    color: #ffffff;
    padding: 5px 17px 8px;

}

.panel-title-fd{
    color: #ffffff;
    font-size: 14px;
    font-weight: 700;
    /*color: #d3eced;*/
    text-transform: uppercase;
    letter-spacing: 1px;
}
</style>






<style type="text/css">
.ui-group-buttons .or{position:relative;float:left;width:.3em;height:1.3em;z-index:3;font-size:12px}
.ui-group-buttons .or:before{position:absolute;top:50%;left:50%;content:'or';background-color:#5a5a5a;margin-top:-.1em;margin-left:-.9em;width:1.8em;height:1.8em;line-height:1.55;color:#fff;font-style:normal;font-weight:400;text-align:center;border-radius:500px;-webkit-box-shadow:0 0 0 1px rgba(0,0,0,0.1);box-shadow:0 0 0 1px rgba(0,0,0,0.1);-webkit-box-sizing:border-box;-moz-box-sizing:border-box;-ms-box-sizing:border-box;box-sizing:border-box}
.ui-group-buttons .or:after{position:absolute;top:0;left:0;content:' ';width:.3em;height:2.84em;background-color:rgba(0,0,0,0);border-top:.6em solid #5a5a5a;border-bottom:.6em solid #5a5a5a}
.ui-group-buttons .or.or-lg{height:1.3em;font-size:16px}
.ui-group-buttons .or.or-lg:after{height:2.85em}
.ui-group-buttons .or.or-sm{height:1em}
.ui-group-buttons .or.or-sm:after{height:2.5em}
.ui-group-buttons .or.or-xs{height:.25em}
.ui-group-buttons .or.or-xs:after{height:1.84em;z-index:-1000}
.ui-group-buttons{display:inline-block;vertical-align:middle}
.ui-group-buttons:after{content:".";display:block;height:0;clear:both;visibility:hidden}
.ui-group-buttons .btn{float:left;border-radius:0}
.ui-group-buttons .btn:first-child{margin-left:0;border-top-left-radius:.25em;border-bottom-left-radius:.25em;padding-right:15px}
.ui-group-buttons .btn:last-child{border-top-right-radius:.25em;border-bottom-right-radius:.25em;padding-left:15px}
</style>

  </center>
  <br>
 </div>
  

























<style type="text/css">
  @import url(http://fonts.googleapis.com/css?family=Karla:700,400);
h1, h2 {
  color: white;
  font-family: 'Karla-Bold', Helvetica Neue, Helvetica, sans-serif;
  font-weight: 700;
  text-align: center;
}

h1 {
  margin-bottom: 0;
}

h2 {
  font-size: 1em;
  margin-top: 0;
  line-height: 1.6em;
}

p {
  font-family: 'Karla-Regular', Helvetica Neue, Helvetica, sans-serif;
  line-height: 1.4em;
  font-weight: 400;
}

.wrapper {
  margin: 0 auto;
  width: 90%;
}

.logo,
.info-panel__main {
  -moz-transform: translateY(3em);
  -ms-transform: translateY(3em);
  -webkit-transform: translateY(3em);
  transform: translateY(3em);
}

.logo {
  background: url("http://mperrotti.com/img/icons.svg") no-repeat #DEDEDE 18px 20px;
  border-radius: 999em;
  border: .75em solid white;
  height: 6em;
  margin: 0 auto;
  position: relative;
  width: 6em;
  z-index: 2;
}

.info-panel .info-panel__main {
  background: #DEDEDE;
  border-radius: .25em .25em 0 0;
  margin-top: -4em;
  padding: 4em 2em 2em 2em;
  position: relative;
  z-index: 1;
}
.info-panel .info-panel__main .info-panel__social {
  margin: 2em auto 0 auto;
  width: 175px;
}
.info-panel .info-panel__main .info-panel__social a {
  display: inline-block;
  vertical-align: middle;
  *vertical-align: auto;
  *zoom: 1;
  *display: inline;
  height: 24px;
  margin: 0 .5em;
  width: 24px;
}
.info-panel .info-panel__main .info-panel__social a[href*="dribbble"] {
  background: url("http://mperrotti.com/img/icons.svg") no-repeat transparent 0 -73px;
}
.info-panel .info-panel__main .info-panel__social a[href*="github"] {
  background: url("http://mperrotti.com/img/icons.svg") no-repeat transparent 0 -108px;
}
.info-panel .info-panel__main .info-panel__social a[href*="twitter"] {
  background: url("http://mperrotti.com/img/icons.svg") no-repeat transparent 0 -144px;
}
.info-panel .info-panel__main .info-panel__social a[href*="last.fm"] {
  background: url("http://mperrotti.com/img/icons.svg") no-repeat transparent 0 -177px;
}
.info-panel .info-panel__bio {
  -moz-transform: translateY(-100%);
  -ms-transform: translateY(-100%);
  -webkit-transform: translateY(-100%);
  transform: translateY(-100%);
  background: #141926;
  max-height: 0em;
  overflow: hidden;
  position: relative;
  z-index: 0;
}
.info-panel .info-panel__bio p {
  border-top: 1px solid white;
  color: white;
  margin: 0 auto;
  padding: 2em 1em;
  width: 70%;
}

.info-panel__pull-tab {
  background: #68c18f;
  border-radius: 0 0 .25em .25em;
  display: block;
  height: 1em;
  position: relative;
  top: 3em;
  /*  &:after {
        content: '';
        position: absolute;
        border-width: 1em 1em 0;
        border-style: solid;
        border-color: $accent transparent;
        bottom: -1em;
        display: block;
        left: 50%;
        margin-left: -1em;
        width: 0;
      }*/
}

/* ------ Expanded info styles ------ */
.logo,
.info-panel__main,
.info-panel__bio {
  -moz-transition: all 0.25s ease;
  -o-transition: all 0.25s ease;
  -webkit-transition: all 0.25s ease;
  transition: all 0.25s ease;
  -webkit-backface-visibility: hidden;
}

.info-panel__pull-tab {
  -moz-transition: all 1s ease;
  -o-transition: all 1s ease;
  -webkit-transition: all 1s ease;
  transition: all 1s ease;
}

.is-expanded .logo,
.is-expanded .info-panel__main,
.is-expanded .info-panel__bio {
  -moz-transition: all 1s ease;
  -o-transition: all 1s ease;
  -webkit-transition: all 1s ease;
  transition: all 1s ease;
  -webkit-backface-visibility: hidden;
}
.is-expanded .info-panel__pull-tab {
  -moz-transition: all 0.25s ease;
  -o-transition: all 0.25s ease;
  -webkit-transition: all 0.25s ease;
  transition: all 0.25s ease;
}
.is-expanded .logo,
.is-expanded .info-panel__main,
.is-expanded .info-panel__bio {
  -moz-transform: translateY(0);
  -ms-transform: translateY(0);
  -webkit-transform: translateY(0);
  transform: translateY(0);
}
.is-expanded .info-panel__bio {
  max-height: 15em;
}
.is-expanded .info-panel__pull-tab {
  top: 0;
}
.is-expanded .info-panel__pull-tab:after {
  border-width: 0 1em 1em;
  bottom: auto;
  top: -1em;
}

</style>